[google]
optimization_sheet_id = "https://docs.google.com/spreadsheets/d/1DdZmbo3tvtrb8fNfgTdgmOpjX-XoKhTcQa1hQLlffPE/edit#gid=769220148"
input_range_name = "Output"
output_range_name = "Output"

[genetic_algorithm]
pop_size = 1000
k = 10
mutation_rate = 0.015
generations = 10000000
num_parents = 10
num_top_parents = 10
