[google]
optimization_sheet_id = "https://docs.google.com/spreadsheets/d/1DdZmbo3tvtrb8fNfgTdgmOpjX-XoKhTcQa1hQLlffPE/edit#gid=769220148"
input_range_name = "Output"
output_range_name = "Output"

[genetic_algorithm]
pop_size = 100
k = 3
mutation_rate = 0.01
generations = 10000000
num_parents = 2
num_top_parents = 2

chunk_size = 10
